### ISSUE TITLE
Add authentication to the API

### ISSUE THREAD

**Issue by avra-m3** [Hammer-Inc/SignMeUp#3]
Before public release authentication will need to be added to prevent unauthorized use.

**Comment by wmundev** [comment]
willing to use firebase for integration?

**Comment by avra-m3** [comment]
Sure! I was thinking about this earlier and Firebase would probably fit well with what I had in mind for this feature.

Essentially, It'd be nice to have a way to allow club executives to sign up students rather than a basic password authentication.

Additionally it would be handy if students could sign themselves up to any club.

Those not authenticated should not be provided with access

(The first part can be future work, for the moment I'd like to aim at putting a layer of authentication between the internet and the API)

**Comment by avra-m3** [comment]
Completed using flask-security, closed in #7
